/** Declaration file generated by dts-gen */

export = express_mysql_session;

declare function express_mysql_session(session: any, ...args: any[]): any;

declare namespace express_mysql_session {
    const prototype: {
    };

}

